### ISSUE TITLE
Mysql repo error when EMX import file contains an attribute specified as TEXT and unique

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#2045]
Error when an attribute is of dataType TEXT and unique=true.
Stacktrace:

	... 23 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB/TEXT column 'name' used in key specification without a key length
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2819)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2768)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:949)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:795)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:1006)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:429)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:402)
	... 25 more

**Comment by Mark-de-Haan** [comment]
"Basically you can not use Text column as UNIQUE key. Because practically such a big column will not be unique and there might be a chance of more duplicates. So go for hashing method and use that output as a UNIQUE constraint." - http://stackoverflow.com/questions/14033378/make-text-column-as-unique-key

Won't fix or hashing solution i guess?

**Comment by dennishendriksen** [comment]
Either MOLGENIS should not allow the combination of unique=true and datatype=text or all backends should deal with this constraint themselves. In the former this should be checked when adding or updating meta data and when importing EMX files.

**Comment by mswertz** [comment]
I would prefer a new data type called 'id' that maps to unique varchar.

**Comment by Mark-de-Haan** [comment]
With the 1000 column import and setting all columns to text, the unique parameter in the EMX file can no longer be used.

**Comment by mswertz** [comment]
I suppose this is now solved by checking unique in data api layer, right?

**Comment by dennishendriksen** [comment]
This is not solved. Uniqueness is checked in the data layer, but uniqueness constraints are still added in the MySqlRepository. I propose we do not allow the combination of TEXT with unique=true, I don't see a use case and the checks can be very expensive.

**Comment by dennishendriksen** [comment]
We could add a AttributeMetaDataRepositoryValidationDecorator to check for illegal combinations. Currently this is done in the importer which causes problems when we start modifying meta data through the REST API or forms.

**Comment by dennishendriksen** [comment]
MySQL not available in 2.0-RC, unique text attributes import successfully in PostgreSQL.
