### ISSUE TITLE
Forms occasionally eat up some of the letters that you've typed

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4315]
In particular when there's a server-side validation in play, on a molgenis vm contacted from the dev machine or build server.

Happens when you type fast, and you can see the letter arriving in the text field and then disappearing again. So "Unique" in a unique string field sometimes results in value "Uniqu". And an id of 55 may end up as 5.

I suspect that the validation requests, one for Unique and one for Uniqu, are racing for which one gets validated first.

To reproduce, create a new typetest entity and rattle into the Id field: 12345.
Expected: the ID you entered is always shown: 12345
Actual: Sometimes you'll get 124 or so.

**Comment by fdlk** [comment]
I noticed that we're working around this when trying to test the forms but it seems to me it's better to fix the bug instead! :)

**Comment by bartcharbon** [comment]
Encountered this again during the creation of a user (type username quickly) during release testing on molgenis62 for the 2.0 release candidate

**Comment by Mark-de-Haan** [comment]
Wontfix: Issue will be adressed in the https://github.com/Mark-de-Haan/molgenis-vue-forms

**Comment by LuukDijkhuis** [comment]
fixed in the new forms

**Comment by fdlk** [comment]
Still happens in the old forms which are not yet completely replaced.
